#COMMON PROFILE
spring:
  messages:
    encoding: UTF-8
  profiles:
    active: local
  application:
    name: Online-meet
  banner:
    charset: UTF-8
    location: banner.txt
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    key-alias: mycert
